#!/bin/sh

# Library directory
LIBDIR="lib"

# If we are launching from a symlink, such as /usr/local/bin/runglest.sh, we need to get where
# the symlink points to
pth="`readlink $0`"

# $pth will be empty if our start path wasnt a symlink
if [ $pth ]; then
	GAMEDIR="`dirname $pth`"
else
	GAMEDIR="`dirname $0`"
fi

# export game library directory
test -n "${LIBDIR}" && export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GAMEDIR}/${LIBDIR}"

echo $*>$GAMEDIR/test.log
$GAMEDIR/bin/glest_g3dviewer "$1"

