#!/bin/sh
# 2014 Written by filux <heross(@@)o2.pl>
# Copyright (c) 2014-2015 under GNU GPL v3.0+
# ----------------------------------------------------------------------------
LANG=C

SCRIPTLOCATION="$(readlink -f "$0")"
GAMEDIR="$(dirname "$SCRIPTLOCATION")"
LIBDIR="lib"
WARNINGS="$($GAMEDIR/start_megaglest --tool-editor 2>&1)"
if [ -d "$GAMEDIR/$LIBDIR" ]; then
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${GAMEDIR}/${LIBDIR}"
fi
BeginTime="$(date +"%s")"
$GAMEDIR/megaglest_editor $@
$GAMEDIR/start_megaglest --tool-buginfo "$?" "$WARNINGS" "$BeginTime" "$(date +"%s")"
