.TH "libirc_options.h" 3 "10 Jan 2009" "Version 1.3" "libircclient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libirc_options.h \- This file defines the options used in irc_session_options().  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLIBIRC_OPTION_DEBUG\fP   (1 << 1)"
.br
.ti -1c
.RI "#define \fBLIBIRC_OPTION_STRIPNICKS\fP   (1 << 2)"
.br
.RI "\fIallows to strip origins automatically. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This file defines the options used in irc_session_options(). 

\fBAuthor:\fP
.RS 4
Georgy Yunaev 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
09.2004 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libircclient from the source code.
