IF(BUILD_MEGAGLEST)
	MESSAGE(STATUS "Will try to build MegaGlest game")

	IF(WIN32)
		IF(NOT VCPKG_TARGET_TRIPLET)
	    INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/source/win32_deps/curl-7.21.3/include)
	  ENDIF()
	ENDIF()

	FIND_PACKAGE(CURL REQUIRED)
	INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIRS})
	IF(UNIX)
	    SET(EXTERNAL_LIBS ${EXTERNAL_LIBS} ${CURL_LIBRARIES})
	ENDIF()

	SET(COMMON_LIBS ${CURL_LIBRARIES})
	ADD_SUBDIRECTORY(shared_lib)
	ADD_SUBDIRECTORY(glest_game)
ENDIF()
