name: Docker Image

on:
  push:
    branches:
      - 'master'
      - 'develop'
    paths:
      - '.github/workflows/docker.yml'
      - 'mk/linux/Dockerfile'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: mk/linux/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/megaglest-build-env:bionic
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/megaglest-build-env:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/megaglest-build-env:buildcache,mode=max
