name: Meson
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ develop ]
    paths:
    - 'source/**/**'
    - '**meson.build'
    - '**/meson.yml'
  pull_request:
    branches: [ develop ]
    paths:
    - 'source/**/**'
    - '**meson.build'
    - '**/meson.yml'

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo mk/linux/setupBuildDeps.sh
        sudo apt install -y --no-install-recommends meson
        # Using pip is only required if a newer version of meson is required
        # sudo apt-get install -y python3-pip python3-setuptools # required for pip
        # sudo -H python3 -m pip install meson ninja
    - name: Build
      run:  |
        mk/test-meson-build.sh

  #freebsd:
    #runs-on: ubuntu-latest
    #name: FreeBSD
    #steps:
    #- uses: actions/checkout@v4
    #- name: Test in FreeBSD
      #id: test
      #uses: vmactions/freebsd-vm@v1
      #with:
        #usesh: true
        #prepare: |
          #pkg install -y \
            #bash \
            #meson \
            #cmake \
            #cppunit \
            #curl \
            #freetype2 \
            #fribidi \
            #ftgl \
            #git \
            #glew \
            #jpeg-turbo \
            #libGLU \
            #libircclient \
            #libogg \
            #libvorbis \
            #libX11 \
            #libxml2 \
            #lua53 \
            #mesa-libs \
            #miniupnpc \
            #openal-soft \
            #pkgconf \
            #png \
            #sdl2 \
            #wx30-gtk3

        #run: |
          #git config --global --add safe.directory /home/runner/work/megaglest-source/megaglest-source
          #cd /usr/local/bin
          #ln -s wxgtk3u-3.0-config wx-config
          #cd -
          #mk/test-meson-build.sh

  #macos:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v4

    #- name: Get dependencies
      #run: |
        #mk/macos/setupBuildDeps.sh

    #- name: Build MegaGlest With Clang Compiler
      #run: |
        #mk/test-meson-build.sh

  MSYS:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          bison
          dos2unix
          flex
          git
        pacboy: >-
          gcc:p
          cmake:p
          ninja:p
          pkgconf:p
          python-certifi:p
        update: true

    - name: Install dependencies
      shell: msys2 {0}
      run: |
        pacman --noconfirm --needed -S \
          mingw-w64-x86_64-libpng \
          mingw-w64-x86_64-meson \
          mingw-w64-x86_64-SDL2

    - name: Build
      shell: msys2 {0}
      run: |
        mk/test-meson-build.sh

